### ISSUE TITLE
Get list of questions to view on front end..

### ISSUE THREAD

**Issue by hsharma89** [Learnosity/learnosity-sdk-asp.net#18]
Hi,
 I am using this API to get data from learnosity. I used DataApi() method from Data.cs class by modifying URL to get questions data. Using that i am able to fetch data on backend, but when viewing on front end,  i am getting following error : -

Error ->  50004: Items API initialization failed. Initialised without a request objectView this error on LearnosityItems.errors[0]

Any solutions to resolve this.

Modified DataApi() method - 

 public static string DataApi()
        {
            string url = "https://data-va.learnosity.com/v2018.1.LTS/itembank/questions";
			

			JsonObject security = new JsonObject();
            security.set("consumer_key", Credentials.ConsumerKey);
            security.set("domain", Credentials.Domain);
			string secret = Credentials.ConsumerSecret;
			string[] arr = new string[] { };

			string json = "[\"123456\"]";
			JsonObject jo = JsonObjectFactory.fromString(json);

			JsonObject request = new JsonObject();
            request.set("limit", 1000);
			request.set("item_references", jo);
			

			string action = "get";
			DataApi da = new DataApi();
            Remote r = da.request(url, security, secret, request, action);
			return r.getBody();
        }

JSON retrieved from this method is attached as image.
![resultjson](https://user-images.githubusercontent.com/22783551/41637849-b6011084-7473-11e8-9223-bb355de5b9ea.png)

**Comment by shtrom** [comment]
Hi @hsharma89,

Could you show how you are trying to render your question data?

I don't think Items API can be used to render questions from static data. You may want to use Questions API instead. That said, Items API should also be able to retrieve and display a full Item and its Questions from the Item Bank, without having to use Data API.

**Comment by shtrom** [comment]
Yes, I think you either need to use Questions API to render your Question JSON this way.

However, this is quite convoluted, I think it'll be easier for you to just use Items API to fetch and display an Item which contains the Questions you want to render. It will do all I understand you want to do in one go.

Would there be a particularl reason for you to use Data+Questions API, rather than Items API?

**Comment by hsharma89** [comment]
Hi,
    I tried Question API, but couldn't get proper result. Can you please tell me front end to show Question API result.

Would there be a particularl reason for you to use Data+Questions API, rather than Items API?
No, just trying to render results.

**Comment by shtrom** [comment]
Could you reach out to our support team http://support.learnosity.com/ ? They should be able to help you out.

As this doesn't seem to be a bug in the SDK, I'll close this issue for now, but feel free to reopen it if it turns out it is a bug.
