### ISSUE TITLE
Getting a "Protocol Error" with no error code

### ISSUE THREAD

**Issue by lorddev** [Learnosity/learnosity-sdk-asp.net#46]
The API [documentation says](https://help.learnosity.com/hc/en-us/articles/360000758677-Rate-Limiting-with-the-Data-API) to check for 429 and wait for 5 seconds. I'm using 

```csharp
var statusCode = remote.getStatusCode();
```
and it just says "ProtocolError".
I tried
```csharp
remote.getError()["code"]
```
as well and it said the same thing.

How do we determine if it's a 429?

Thanks.

**Comment by BigFeast** [comment]
Can we spin up a load test app in linqpad to hit the api in a multi task loop in the dev learnosity api and have a try catch to catch the 429 so we can inspect the result object (Remote)?

**Comment by lorddev** [comment]
While doing load tests I discovered a null reference exception on line 200 of Remote.cs
```csharp
                using (this.result = e.Response)
                {
                    using (StreamReader sr = new StreamReader(this.result.GetResponseStream())) // this.result is NULL
                    {
                        this.responseBody = sr.ReadToEnd();
                    }
                }
                this.status = e.Status.ToString();
                this.errorCode = this.status;
                this.errorMessage = e.Message;
```
where `this.result` is null so it can't get the response stream.

Note that if you check for null before getting the body, you are unable to populate the `meta` field because the server doesn't return it.

**Comment by lorddev** [comment]
Bump?
